# Generated by Django 5.0.1 on 2024-01-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(related_name="tasks", to="task_manager.tag"),
        ),
    ]
